const assert=require('node:assert/strict');
const learning=require('../dist/learning.js');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9);
assert.equal(learning.cases.length,3);
assert.ok(Object.isFrozen(learning.cases[0].settings));
close(learning.gradePrediction('rare',90).actual,9/58.5*100);
close(learning.gradePrediction('rare',90).error,90-9/58.5*100);
close(learning.gradePrediction('common',80).actual,180/220*100);
close(learning.gradePrediction('specific',50).actual,9/18.9*100);
assert.equal(learning.gradePrediction('rare',15.4).close,true);
assert.equal(learning.gradePrediction('rare',90).close,false);
for(const guess of [0,100])assert.ok(Number.isFinite(learning.gradePrediction('rare',guess).error));
for(const guess of ['',null,undefined,NaN,Infinity,-.1,100.1,'15'])assert.throws(()=>learning.gradePrediction('rare',guess),RangeError);
assert.throws(()=>learning.gradePrediction('missing',50),RangeError);
const answers=[{caseId:'rare',prediction:90,denominator:'cases',explanation:'private learner words',arbitrary:'secret'}];
const notebook=learning.notebook(answers);
assert.equal(notebook.attempts.length,1);assert.equal(notebook.attempts[0].prediction,90);
assert.equal(notebook.attempts[0].denominator,'cases');
assert.equal(JSON.stringify(notebook).includes('private learner words'),false);
assert.equal(JSON.stringify(notebook).includes('secret'),false);
assert.equal(notebook.attempts[0].settings.prevalence,1);
assert.equal(learning.notebook([]).attempts.length,0);
assert.deepEqual(answers,[{caseId:'rare',prediction:90,denominator:'cases',explanation:'private learner words',arbitrary:'secret'}]);
console.log(JSON.stringify({result:'PASS',checks:['three case calculations','first guess error','immutable content','invalid guesses','text-free notebook','empty notebook']}));
